django_website/urls.py
#####################################################

#GENERAL WEBSITE URLS 


######################################################


from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from home import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('place/', include('place.urls')),
    path('home/', include('home.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('about/', include ('home.urls')),
    path('contact/', include('home.urls')),
    path('place/', include('home.urls')),
    path('user/', include('user.urls')),
    path('place/<int:id>/<slug:slug>/', include('home.urls')),
    path('logout/', views.logout_view, name="logout_view"),
    path('login/', views.login_view, name="login_view"),
    path('signup/', views.signup_view, name="signup_view"),
]

if settings.DEBUG: #new
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    

home/urls.py
#####################################################

#HOME APPLICATION URLS


######################################################

from django.urls import path

from . import views

urlpatterns=[
	
	# ex: /home/
	path('',views.index,name="index"),
	# ex: /about/
	path('about', views.about, name="about"),
	# ex: /contact/
	path('contact', views.contact, name="contact"),
	# ex:/place/
	path('place', views.place, name="place"),
	# ex:/place/1/statue
	path('place/<int:id>/<slug:slug>', views.placeDetail, name="placeDetail"),
	# ex:/error/
	path('error', views.error, name="error"),
	# ex:/faq/
	path('faq',views.faq, name="faq"),
]

user/urls.py
from django.urls import path
from . import views
####################################################################

#PLACE APPLICATION URLS

####################################################################

urlpatterns=[

	# ex: /user/
	path('',views.index,name="index"),
	# ex:/user/profile
	path('profile', views.profile, name="profile"),
	# ex:/user/profile_edit
	path('profile_edit', views.profile_edit, name="profile_edit"),
	# ex:/user/change_password
	path('change_password', views.change_password, name="change_password"),
	# ex:/user/deletecomment/1
	path('deletecomment/<int:id>', views.deletecomment, name="deletecomment"),
	# ex:/user/addcontent
	path('addcontent', views.addcontent, name="addcontent"),
	# ex:/user/editplace/1
	path('editplace/<int:id>', views.editplace, name="editplace"),
	#ex: /user/deleteplace/1
	path('deleteplace/<int:id>', views.deleteplace, name="deleteplace"),
	#ex: /user/placeimage/1
	path('placeimage/<int:id>', views.placeimage, name="placeimage"),

]

home/models.py
from django.db import models
from django.forms import ModelForm
from ckeditor_uploader.fields import RichTextUploadingField
from django.contrib.auth.models import User
from django.utils.safestring import mark_safe
# Create your models here.

############################################################################################################

#Home FRONTEND MODELS

###########################################################################################################

class Setting(models.Model):

	STATUS=(

		('True','Active'),
		('False','Inactive'),
	)

	title=models.CharField(max_length=150)
	keywords=models.CharField(max_length=255)
	description=models.CharField(max_length=255)
	company=models.CharField(max_length=50)
	address=models.CharField(max_length=255)
	phone=models.CharField(max_length=25)
	fax=models.CharField(max_length=25)
	email=models.CharField(max_length=50)
	smtpserver=models.CharField(max_length=50)
	smtpemail=models.CharField(max_length=50)
	smtppassword=models.CharField(max_length=50)
	smtpport=models.CharField(max_length=5)
	icon=models.ImageField(blank=True, upload_to='images/')
	facebook=models.CharField(max_length=50)
	instagram=models.CharField(max_length=50)
	twitter=models.CharField(max_length=50)
	aboutus=RichTextUploadingField()
	contact=RichTextUploadingField()
	status=models.CharField(max_length=10, choices=STATUS)
	created_at=models.DateTimeField(auto_now_add=True)
	updated_at=models.DateTimeField(auto_now=True)

	def __str__(self):
		return self.title

class ContactFormMessage(models.Model):

	STATUS=(

		('New', 'New'),
		('Read', 'Read'),
	)
	
	name=models.CharField(blank=True,max_length=50)
	email=models.CharField(blank=True,max_length=50)
	subject=models.CharField(blank=True,max_length=50)
	message=models.CharField(blank=True,max_length=255)
	status=models.CharField(max_length=10, choices=STATUS, default='New')
	ip= models.CharField(blank=True, max_length=20)
	note=models.CharField(blank=True, max_length=100)
	created_at=models.DateTimeField(auto_now_add=True)
	updated_at=models.DateTimeField(auto_now=True)

	def __str__(self):
		return self.name

class ContactForm(ModelForm):

	class Meta:
		model=ContactFormMessage
		fields=['name','email','subject','message', 'ip']

class UserProfile(models.Model):

	user=models.OneToOneField(User, on_delete=models.CASCADE)
	phone=models.CharField(blank=True, max_length=20)
	city=models.CharField(blank=True, max_length=20)
	country=models.CharField(blank=True, max_length=20)
	image=models.ImageField(blank=True,upload_to='images/users/')

	def __str__(self):
		return self.user.username

	def user_name(self):
		return self.user.first_name + ' ' + self.user.last_name + '[' + self.user.username + ']'

	def image_tag(self):
		return mark_safe('<img src="{}" height="50" />'.format(self.image.url))
	image_tag.short_description='Image'


class UserProfileForm(ModelForm):

	class Meta:
		model=UserProfile
		fields=['phone','city','country','image']


class Faq(models.Model):

	STATUS=(

		('True','Active'),
		('False', 'Inactive'),
	)

	orderNo=models.IntegerField()
	question=models.CharField(max_length=255)
	answer=models.TextField()
	status=models.CharField(max_length=10, choices=STATUS)
	created_at=models.DateTimeField(auto_now_add=True)
	updated_at=models.DateTimeField(auto_now=True)

	def __str__(self):
		return self.question

user/models.py
from django.db import models
from django.forms import ModelForm
from django.contrib.auth.models import User
from place.models import Place
# Create your models here.

user/forms.py
from django import forms
from django.contrib.auth.forms import UserChangeForm
from django.contrib.auth.models import User
from home.models import UserProfile
from django.forms import FileInput
from place.models import Place
from ckeditor.widgets import CKEditorWidget
from django.forms import ModelForm




class UserUpdateForm(UserChangeForm):

	class Meta:
		model=User
		fields=('username', 'email', 'first_name', 'last_name',)

class ProfileUpdateForm(forms.ModelForm):

	class Meta:
		model=UserProfile
		fields=('phone', 'city', 'country', 'image',)
		

class UserContentForm(ModelForm):

	class Meta:
		model= Place
		fields=['category', 'title',  'slug', 'keywords', 'description', 'image', 'detail']
		widgets={

			'title': forms.TextInput(attrs={'class':'input'}),
			'slug': forms.TextInput(attrs={'class':'input'}),
			'keywords': forms.TextInput(attrs={'class':'input'}),
			'description': forms.TextInput(attrs={'class':'input'}),
			'image': forms.FileInput(attrs={'class':'input'}),
			'detail':CKEditorWidget(),
		}

user/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from home.models import UserProfile
from place.models import Category, Comment, Place, UserContentImageForm, Images
from .forms import UserUpdateForm, ProfileUpdateForm
from django.contrib import messages
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.decorators import login_required
from .forms import UserContentForm


# Create your views here.

def index(request):
	return HttpResponseRedirect("/user/profile")

@login_required(login_url='/login')
def profile(request):

	current_user=request.user
	profile= UserProfile.objects.get(user_id=current_user.id)
	categories=Category.objects.all()
	comments=Comment.objects.filter(user_id=current_user.id).order_by('-id')
	places=Place.objects.filter(user_id=current_user.id).order_by('-id')
	content={ 'profile':profile, 'categories':categories, 'comments':comments, 'places':places,}
	return render(request, 'profile.html',content)

@login_required(login_url='/login')
def profile_edit(request):

	if request.method=='POST':
		user_form=UserUpdateForm(request.POST, instance=request.user)
		profile_form=ProfileUpdateForm(request.POST, request.FILES, instance=request.user.userprofile)
		if user_form.is_valid() and profile_form.is_valid():
			user_form.save()
			profile_form.save()
			messages.success(request,"Profile Updated Successfully.")
			return HttpResponseRedirect('/user/profile')
		else:
			messages.warning(request,form.errors)
			return HttpResponseRedirect('/user/profile_edit')
	else:
		categories=Category.objects.all()
		current_user=request.user
		user_form=UserUpdateForm(instance=request.user)
		profile_form=ProfileUpdateForm(instance=request.user.userprofile)
		profile=UserProfile.objects.get(user_id=current_user.id)
		content={'categories':categories, 'profile':profile, 'profile_form':profile_form }
		return render(request, 'profile_edit.html', content)


@login_required(login_url='/login')
def change_password(request):

	if request.method=='POST':
		form=PasswordChangeForm(request.user, request.POST)
		if form.is_valid():
			user=form.save()
			update_session_auth_hash(request,user)
			messages.success(request,"Password changed successfully.")
			return HttpResponseRedirect('/user/change_password')
		else:
			messages.warning(request, "Please Correct the Error Below. <br>" + str(form.errors))
			return HttpResponseRedirect('/user/change_password')
	else:
		categories=Category.objects.all()
		form=PasswordChangeForm(request.user)
		content={'form':form, 'categories':categories}
		return render(request, 'password_change.html', content)


@login_required(login_url='/login')
def user_comments(request):

	categories=Category.objects.all()
	current_user=request.user
	comments=Comment.objects.filter(user_id=current_user.id)
	content={'categories':categories, 'comments':comments, }
	return render(request, 'profile.html', content)


@login_required(login_url='/login')
def deletecomment(request,id):

	current_user=request.user
	Comment.objects.filter(id=id, user_id=current_user.id).delete()
	messages.success(request, "Comment deleted successfully")
	return HttpResponseRedirect('/user/profile')


@login_required(login_url='/login')
def user_places(request):

	categories=Category.objects.all()
	current_user=request.user
	places=Place.objects.filter(user_id=current_user.id)
	content={'categories':categories, 'places':places, }
	return render(request, 'profile.html', content)



@login_required(login_url='/login')
def addcontent(request):

	form= UserContentForm(request.POST, request.FILES)
	if request.method=='POST':
		if form.is_valid():
			current_user=request.user
			data=Place()
			data.user_id=current_user.id
			data.category=form.cleaned_data['category']
			data.title=form.cleaned_data['title']
			data.keywords=form.cleaned_data['keywords']
			data.description=form.cleaned_data['description']
			data.image=form.cleaned_data['image']
			data.slug=form.cleaned_data['slug']
			data.detail=form.cleaned_data['detail']
			data.status='False'
			data.save()
			messages.success(request, "Your Place is Added Successfully.")
			return HttpResponseRedirect('/user/profile')
		else:
			messages.warning(request, "Please Correct the Error in Places Section. <br>" + str(form.errors))
			return HttpResponseRedirect('/user/addcontent')
	else:
		categories=Category.objects.all()
		content={'categories':categories, 'form':form,}
		return render(request, 'add-content.html', content)

@login_required(login_url='/login')
def editplace(request,id):
	
	place=Place.objects.get(id=id)
	if request.method=='POST':
		form=UserContentForm(request.POST, request.FILES, instance=place)
		if form.is_valid():
			form.save()
			messages.success(request, "Your Place is Updated Successfully.")
			return HttpResponseRedirect('/user/profile')
		else:
			messages.warning(request, "Please Correct the Error in Places Section. <br>" + str(form.errors))
			return HttpResponseRedirect('/user/editplace/'+str(id))
	else:
		categories=Category.objects.all()
		form=UserContentForm(instance=place)
		content={'categories':categories, 'form':form,}
		return render(request, 'add-content.html',content)


@login_required(login_url='/login')
def deleteplace(request,id):

	current_user=request.user
	Place.objects.filter(id=id, user_id=current_user.id).delete()
	messages.success(request, 'Place Deleted Successfully.')
	return HttpResponseRedirect('/user/profile')


def placeimage(request,id):
	if request.method=='POST':
		lasturl=request.META.get('HTTP_REFERER')
		form=UserContentImageForm(request.POST, request.FILES)
		if form.is_valid():
			data=Images()
			data.title=form.cleaned_data['title']
			data.place_id=id
			data.image=form.cleaned_data['image']
			data.save()
			messages.success(request, "Your image is added to the gallery.")
			return HttpResponseRedirect(lasturl)
		else:
			messages.warning(request, "Image Upload Error :" + str(form.errors))
			return HttpResponseRedirect(lasturl)
	else:

		places=Place.objects.get(id=id)
		images=Images.objects.filter(place_id=id)
		form=UserContentImageForm()
		content={'places':places, 'images':images,'form':form}
		return render(request, 'user_place_gallery.html', content)

user/templates/add-content.html
{% extends 'homebase.html' %}
{% block title %} Add Your Place || Absolute Journey {% endblock %}
{% block inner_headline %}

	<section id="inner-headline">
      <div class="container">
        <div class="row">
          <div class="span4">
            <div class="inner-heading">
              <h2>Add Place</h2>
            </div>
          </div>
          <div class="span8">
            <ul class="breadcrumb">
              <li><a href="/"><i class="icon-home"></i></a><i class="icon-angle-right"></i></li>
              <li class="active">Add Place</li>
            </ul>
          </div>
        </div>
      </div>
    </section>


{% endblock %}

{% block main_content %}

<div class="row">
    <div class="span12">
        <h4>Add Your <strong>Place</strong></h4>

        {% if messages %}
          {% for message in messages %}
              <div class="alert alert-{{message.tags}}" role="alert">
                {{ message }}
              </div>
          {% endfor %}
        {% endif %}

        <form method="post" enctype="multipart/form-data" class="contactForm">   
            {% csrf_token %}
            {{ form.media }}
            {{ form.as_p }}
            <p class="span8 text-center">
              <button class="btn btn-large btn-theme margintop10" type="submit">Save</button>
            </p>
        </form>
    </div>
</div>


{% endblock %}

user/templates/password_change.html
{% extends 'homebase.html' %}

{% block title %} Change Password || Absolute Journey {% endblock %}

{% block inner_headline %} 

<section id="inner-headline">
    <div class="container">
        <div class="row">
            <div class="span4">
                <div class="inner-heading">
                    <h2>Change Password</h2>
                </div>
            </div>
            <div class="span8">
                <ul class="breadcrumb">
                    <li><a href="/"><i class="icon-home"></i></a><i class="icon-angle-right"></i></li>
                    <li class="active">Change Password</li>
                </ul>
            </div>
        </div>
    </div>
</section>

{% endblock %}

{% block main_content %}

<div class="row">
    <div class="span12">
        <h4>Change Your <strong>Password</strong></h4>

        {% if messages %}
          {% for message in messages %}
              <div class="alert alert-{{message.tags}}" role="alert">
                {{ message|safe }}
              </div>
          {% endfor %}
        {% endif %}

        <form method="post" class="contactForm">   
            {% csrf_token %}
            {{ form.as_p }}
                <p class="span8">
                    <button class="btn btn-large btn-theme margintop10" type="submit">Change</button>
                </p>
            </div>
        </form>


</div>
</div>
{% endblock %}

user/templates/profile.html
{% extends 'homebase.html' %}

{% block title %} {{ user.first_name }} {{ user.last_name }} Profile || Absolute Journey {% endblock %}

{% block inner_headline %}

<section id="inner-headline">
    <div class="container">
        <div class="row">
            <div class="span4">
                <div class="inner-heading">
                    <h2>{{ user.first_name }} {{ user.last_name }} Profile</h2>
                </div>
            </div>
            <div class="span8">
                <ul class="breadcrumb">
                    <li><a href="/"><i class="icon-home"></i></a><i class="icon-angle-right"></i></li>
                    <li class="active">{{ user.first_name }} {{ user.last_name }} Profile</li>
                </ul>
            </div>
        </div>
    </div>
</section>

{% endblock %}

{% block main_content %}

              <div class="span12">
                <h4>User <strong>Panel</strong></h4>
                <div class="tabbable tabs-left">
                  <ul class="nav nav-tabs">
                    <li class="active"><a href="#topone" data-toggle="tab">Settings</a></li>
                    <li><a href="#toptwo" data-toggle="tab">Comments</a></li>
                    <li><a href="#topthree" data-toggle="tab">Places</a></li>
                  </ul>
                  <div class="tab-content">
                    <div class="tab-pane active" id="topone">
                      
                   <div class="span8">
                    {% if messages %}
          {% for message in messages %}
              <div class="alert alert-{{message.tags}}" role="alert">
                {{ message }}
              </div>
          {% endfor %}
        {% endif %}

            <table class="table">

            	<tr>
            		<th></th>
            		<td><img style="height: 200px; width: 200px;" src="{{ profile.image.url }}"></td>
            	</tr>
            	<tr>
            		<th>Name Surname</th>
            		<td>{{ profile.user.first_name }} {{ profile.user.last_name }}</td>
            	</tr>
            	<tr>
            		<th>Username</th>
            		<td>{{ profile.user.username }}</td>
            	</tr>
            	<tr>
            		<th>Email</th>
            		<td>{{ profile.user.email }}</td>
            	</tr>
            	<tr>
            		<th>Phone</th>
            		<td>{{ profile.phone }}</td>
            	</tr>
            	<tr>
            		<th>City</th>
            		<td>{{ profile.city }}</td>
            	</tr>
            	<tr>
            		<th>Country</th>
            		<td>{{ profile.country }}</td>
            	</tr>
            	<tr>
            		<th><a href="/user/profile_edit"><button class="btn-info" type="submit">Edit</button></a> <a href="/user/change_password"><button class="btn-info" type="submit">Change Password</button></a> </th>
            		<td></td>
            	</tr>

            </table>
          </div>
                    </div>
                    <div class="tab-pane" id="toptwo">
                      
                      {% if messages %}
                        {% for message in messages %}
                          <div class="alert alert-{{message.tags}}" role="alert">
                            {{ message }}
                          </div>
                        {% endfor %}
                      {% endif %}

                      <table class="table">
                        <tr>
                          <th>Place</th>
                          <th>Subject</th>
                          <th>Comment</th>
                          <th>Rate</th>
                          <th>Status</th>
                          <th>Date</th>
                          <th>Operation</th>
                        </tr>
                        {% if comments %}
                          {% for comment in comments %}
                            <tr>
                              <td> <a href="/place/{{ comment.place.id }}/{{ comment.place.slug }}">{{ comment.place.title }}</a></td>
                              <td>{{ comment.subject }}</td>
                              <td>{{ comment.comment }}</td>
                              <td>{{ comment.rate }}</td>
                              <td>{{ comment.status }}</td>
                              <td>{{ comment.created_at }}</td>
                              <td><button type="submit"><a href="/user/deletecomment/{{ comment.id }}" onclick="return confirm('You are about to delete a comment. Are you sure?')">Delete</a></button></td>
                            </tr>
                          {% endfor %}
                        {% else %}
                          <tr>
                            <td colspan="7">You have no comment available</td>
                          </tr>
                        {% endif %}
                      </table>

                    </div>
                    <div class="tab-pane" id="topthree">
                      {% if messages %}
                        {% for message in messages %}
                          <div class="alert alert-{{message.tags}}" role="alert">
                            {{ message }}
                          </div>
                        {% endfor %}
                      {% endif %}

                      <div>
                        
                        <a href="/user/addcontent"><button class="btn-info">Add a New Place</button></a>

                      </div>
                      <table style="margin-top: 10px;" class="table">
                        <tr>
                          <th>Image</th>
                          <th>Title</th>
                          <th>Gallery</th>
                          <th>Description</th>
                          <th>Status</th>
                          <th>Date</th>
                          <th colspan="2">Operation</th>
                        </tr>
                        {% if places %}
                          {% for place in places %}
                            <tr>
                              <td> <a href="/place/{{ place.id }}/{{ place.slug }}"><img style="height: 150px; width: 150px;" src="{{ place.image.url }}"></a> </td>
                              <td> <a href="/place/{{ place.id }}/{{ place.slug }}">{{ place.title }}</a></td>
                              <td> <a href="javascript:;" onclick="window.open('/user/placeimage/{{ place.id }}', 'gallery', 'height=600, width=800, top=50, left=150')">
                                <img style="height: 50px; width: 50px;" src="/uploads/images/gallery.png">
                              </a></td>
                              <td>{{ place.description }}</td>
                              <td>{{ place.status }}</td>
                              <td>{{ place.created_at }}</td>
                              <td><button type="submit"><a href="/user/editplace/{{ place.id }}">Edit</a></button></td>
                              <td><button type="submit"><a href="/user/deleteplace/{{ place.id }}" onclick="return confirm('You are about to delete a place. Are you sure?')">Delete</a></button></td>
                            </tr>
                          {% endfor %}
                        {% else %}
                          <tr>
                            <td colspan="7">You have no places available</td>
                          </tr>
                        {% endif %}
                      </table>
                    </div>
                  </div>
                </div>
                <!-- end tab -->
              </div>

{% endblock %}

user/templates/profile_edit.html
{% extends 'homebase.html' %}
{% block title %} Profile Edit || Absolute Journey {% endblock %}

{% block inner_headline %}

<section id="inner-headline">
    <div class="container">
        <div class="row">
            <div class="span4">
                <div class="inner-heading">
                    <h2>{{ user.first_name }} {{ user.last_name }} Profile Edit</h2>
                </div>
            </div>
            <div class="span8">
                <ul class="breadcrumb">
                    <li><a href="/"><i class="icon-home"></i></a><i class="icon-angle-right"></i></li>
                    <li class="active">{{ user.first_name }} {{ user.last_name }} Profile Edit</li>
                </ul>
            </div>
        </div>
    </div>
</section>

{% endblock %}

{% block main_content %}

<div class="row">
    <div class="span12">
        <h4>Update Your <strong>Profile</strong></h4>

        {% if messages %}
          {% for message in messages %}
              <div class="alert alert-{{message.tags}}" role="alert">
                {{ message }}
              </div>
          {% endfor %}
        {% endif %}

        <form method="post" enctype="multipart/form-data" class="contactForm">   
            {% csrf_token %}
            <img style="height: 200px; width: 200px; border-radius: 20px; margin-bottom: 10px;" src="{{ profile.image.url }}">

            <div class="row">
            	<div class="span8 form-group">
                	<label>Image</label> 
                	<input type="file" name="image" class="input" accept="images/users/*">
                </div>
                <div class="span8 form-group">
                	<label class="control-label" for="inputText">Username</label>
                    <input type="text" name="username" class="form-control" value="{{ profile.user.username }}"/>
                </div>
                <div class="span8 form-group">
                	<label class="control-label" for="inputText">First Name</label>
                    <input type="text" class="form-control" name="first_name" value="{{ profile.user.first_name }}"  />
                </div>
                <div class="span8 form-group">
                	<label class="control-label" for="inputText">Last Name</label>
                    <input type="text" class="form-control" name="last_name" value="{{ profile.user.last_name }}" />
                </div>
                <div class="span8 form-group">
                	<label class="control-label" for="inputText">Email</label>
                    <input type="email" class="form-control" name="email" value="{{ profile.user.email }}" />
                </div>
                <div class="span8 form-group">
                	<label class="control-label" for="inputText">Phone</label>
                    <input type="text" class="form-control" name="phone" value="{{ profile.phone }}" />
                </div>
                <div class="span8 form-group">
                	<label class="control-label" for="inputText">City</label>
                    <input type="text" class="form-control" name="city" value="{{ profile.city }}" />
                </div>
                <div class="span8 form-group">
                	<label class="control-label" for="inputText">Country</label>
                    <input type="text" class="form-control" name="country" value="{{ profile.country }}" />
                </div>
                <p class="span8 text-center">
                    <button class="btn btn-large btn-theme margintop10" type="submit">Update</button>
                </p>
            </div>
        </form>
    </div>
</div>


{% endblock %}

{% block css %}

{% endblock %}

{% block js %}

{% endblock %}

user/templates/user_place_gallery.html
<!DOCTYPE html>
<html>
<head>
	<title>Place Gallery || Absolute Journey</title>
	{% load static %}
    <link href="https://fonts.googleapis.com/css?family=Noto+Serif:400,400italic,700|Open+Sans:300,400,600,700" rel="stylesheet">
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet" />
    <link href="{% static 'css/bootstrap-responsive.css' %}" rel="stylesheet" />
    <link href="{% static 'css/fancybox/jquery.fancybox.css' %}" rel="stylesheet">
    <link href="{% static 'css/jcarousel.css' %}" rel="stylesheet" />
    <link href="{% static 'css/flexslider.css' %}" rel="stylesheet" />
    <link href="{% static 'css/style.css' %}" rel="stylesheet" />
    <!-- Theme skin -->
    <link href="{% static 'skins/default.css' %}" rel="stylesheet" />
    <!-- Fav and touch icons -->
	<script src="{% static 'js/jquery.js' %}"></script>
    <script src="{% static 'js/jquery.easing.1.3.js' %}"></script>
    <script src="{% static 'js/bootstrap.js' %}"></script>
    <script src="{% static 'js/jcarousel/jquery.jcarousel.min.js' %}"></script>
    <script src="{% static 'js/jquery.fancybox.pack.js' %}"></script>
    <script src="{% static 'js/jquery.fancybox-media.js' %}"></script>
    <script src="{% static 'js/google-code-prettify/prettify.js' %}"></script>
    <script src="{% static 'js/portfolio/jquery.quicksand.js' %}"></script>
    <script src="{% static 'js/portfolio/setting.js' %}"></script>
    <script src="{% static 'js/jquery.flexslider.js' %} "></script>
    <script src="{% static 'js/jquery.nivo.slider.js' %}"></script>
    <script src="{% static 'js/modernizr.custom.js' %}"></script>
    <script src="{% static 'js/jquery.ba-cond.min.js' %}"></script>
    <script src="{% static 'js/jquery.slitslider.js' %}"></script>
    <script src="{% static 'js/animate.js' %}"></script>

    <!-- Template Custom JavaScript File -->
    <script src="{% static 'js/custom.js' %}"></script>
 
</head>
<body>

<h2>{{ places.title }}</h2>
<hr>
	{% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{message.tags}}" role="alert">
    			{{ message|safe }}
            </div>
        {% endfor %}
    {% endif %}

    <form method="post" enctype="multipart/form-data">
    	
    	{% csrf_token %}
    	<input type="hidden" name="place_id" id="id_place_id" value="{{ places.id }}">
    	<label for="id_title">Title:</label>
    	<input type="text" name="title" class="input" placeholder="title" maxlength="50" id="id_title">
    	<label for="id_image">Image:</label>
    	<input type="file" name="image" class="input" accept="image/*" id="id_image">
    	<button class="btn btn-success" type="submit">Upload</button>
    </form>

<hr>

<h4>Available Images</h4>

{% if images %}
              <section id="projects">
                <ul id="thumbs" class="portfolio">
                  <!-- Item Project and Filter Name -->
                  <!-- End Item Project -->
                  <!-- Item Project and Filter Name -->
                  {% for image in images %}
                  <li class="item-thumbs span3 design" data-id="id-1" data-type="icon">
                    <!-- Fancybox - Gallery Enabled - Title - Full Image -->
                    <a class="hover-wrap fancybox" data-fancybox-group="gallery" title="{{ image.title }}" href="{{image.image.url}}">
						<span class="overlay-img"></span>
						<span class="overlay-img-thumb font-icon-plus"></span>
						</a>
                    <!-- Thumb Image and Description -->
                    <img style="height: 150px; width: 250px;" src="{{ image.image.url }}" alt="{{ places.title }}">
                  </li>
                  {% endfor %}
                 </ul>
             </section>
	
{% else %}
	You have no available images
{% endif %}

</body>
</html>